# Generated by Django 4.2.11 on 2026-05-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cpu_threshold', models.FloatField(default=80.0, help_text='CPU usage threshold %')),
                ('memory_threshold', models.FloatField(default=85.0, help_text='Memory usage threshold %')),
                ('disk_threshold', models.FloatField(default=90.0, help_text='Disk usage threshold %')),
                ('monitoring_enabled', models.BooleanField(default=True)),
                ('check_interval', models.IntegerField(default=5, help_text='Check interval in seconds')),
                ('data_retention_days', models.IntegerField(default=30, help_text='Days to retain historical data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Monitoring Configs',
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_percent', models.FloatField(help_text='CPU usage percentage')),
                ('cpu_count', models.IntegerField(help_text='Number of CPU cores')),
                ('memory_total', models.BigIntegerField(help_text='Total memory in bytes')),
                ('memory_used', models.BigIntegerField(help_text='Used memory in bytes')),
                ('memory_percent', models.FloatField(help_text='Memory usage percentage')),
                ('disk_total', models.BigIntegerField(help_text='Total disk space in bytes')),
                ('disk_used', models.BigIntegerField(help_text='Used disk space in bytes')),
                ('disk_percent', models.FloatField(help_text='Disk usage percentage')),
                ('network_bytes_sent', models.BigIntegerField(default=0)),
                ('network_bytes_recv', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='monitoring__timesta_67d81a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pid', models.IntegerField(help_text='Process ID')),
                ('name', models.CharField(help_text='Process name', max_length=255)),
                ('status', models.CharField(help_text='Process status', max_length=50)),
                ('cpu_percent', models.FloatField(help_text='CPU usage percentage')),
                ('memory_mb', models.FloatField(help_text='Memory usage in MB')),
                ('num_threads', models.IntegerField(help_text='Number of threads')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp', '-memory_mb'],
                'indexes': [models.Index(fields=['-timestamp'], name='monitoring__timesta_8aa1f9_idx'), models.Index(fields=['pid'], name='monitoring__pid_0a584a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExamNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.CharField(blank=True, help_text='Optional student identifier', max_length=255)),
                ('exam_id', models.CharField(blank=True, help_text='Optional exam identifier', max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['active'], name='monitoring__active_e15252_idx'), models.Index(fields=['student_id'], name='monitoring__student_f92d5c_idx'), models.Index(fields=['exam_id'], name='monitoring__exam_id_9a3e4f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExamActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('student_id', models.CharField(default='unknown', help_text='Student identifier', max_length=255)),
                ('exam_id', models.CharField(default='exam1', help_text='Exam identifier', max_length=255)),
                ('event_type', models.CharField(choices=[('tab_hidden', 'Tab Hidden'), ('tab_visible', 'Tab Visible'), ('lost_focus', 'Window Lost Focus'), ('gained_focus', 'Window Gained Focus'), ('idle', 'Idle'), ('active', 'Active'), ('page_unload', 'Page Unload'), ('exam_loaded', 'Exam Loaded')], max_length=50)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='monitoring__timesta_7464b6_idx'), models.Index(fields=['student_id'], name='monitoring__student_cba5c6_idx'), models.Index(fields=['exam_id'], name='monitoring__exam_id_1d5b24_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alert_type', models.CharField(choices=[('cpu_high', 'High CPU Usage'), ('memory_high', 'High Memory Usage'), ('disk_high', 'High Disk Usage'), ('process_crash', 'Process Crash'), ('network_issue', 'Network Issue'), ('custom', 'Custom Alert')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='monitoring__timesta_53f01c_idx'), models.Index(fields=['is_resolved'], name='monitoring__is_reso_a46808_idx')],
            },
        ),
    ]
